name: "Hello Actions"
%usuniecie kilku linii kodu: 
inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
%dodanie kilku
%linijek kodu
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
